package duplicatesearcher;

public enum ProcessingFlags
{
	SPELL_CORRECTION,
	STEMMING,
	STOP_LIST_COMMON,
	STOP_LIST_GITHUB,
	STOP_LIST_TEMPLATE_STATIC,
	STOP_LIST_TEMPLATE_DYNAMIC,
	PARSE_COMMENTS,
	SYNONYMS,
	FILTER_BAD
}
