package duplicatesearcher;

public enum ProcessingFlags
{
	PARSE_COMMENTS,
	SPELL_CORRECTION,
	STOP_LIST_COMMON,
	STOP_LIST_GITHUB,
	STOP_LIST_TEMPLATE_STATIC,
	STOP_LIST_TEMPLATE_DYNAMIC,
	SYNONYMS,
	STEMMING,
	FILTER_BAD
}
